output_dir: /scratch/ulab222/multi-view/1-gpu/torchprotein_output/

dataset:
  class: SecondaryStructure
  path: /scratch/ulab222/multi-view/1-gpu/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 500  # old value 550 was causing errors
        random: True
      - class: ProteinView
        view: "residue"

test_split: cb513

task:
  class: NodePropertyPrediction
  model:
    class: ESM
    path: /scratch/ulab222/multi-view/1-gpu/esm-model-weights/
    model: ESM-1b
  criterion: ce
  metric: ["micro_acc", "macro_acc"]
  num_mlp_layer: 2
  num_class: 3

eval_metric: macro_acc

optimizer:
  class: Adam
  lr: 2.0e-4

lr_ratio: 0.1

engine:
  gpus: [0]
  batch_size: 4

train:
  num_epoch: 100
