output_dir: /scratch/ulab222/multi-view/pretrain-test/torchprotein_output/

dataset:
  class: BinaryLocalization
  path: /scratch/ulab222/multi-view/pretrain-test/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: /scratch/ulab222/multi-view/pretrain-test/esm-model-weights/
    model: ESM-1b
    readout: mean
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  #gpus: [0, 1, 2, 3]
  batch_size: 32

train:
  num_epoch: 100